print('Digite algo: ')
var = input()
print(" '{}' É um número? : " .format(var), var.isnumeric())
print(" '{}' Só possui espaços? : " .format(var), var.isspace())
print(" '{}' É string? : " .format(var), var.isalpha())
print(" '{}' É ascii? : " .format(var), var.isascii())
print(" '{}' Está em minúsculo? : " .format(var), var.islower())
print(" '{}' Está em maiúsculo? : " .format(var), var.isupper())
print(" '{}' É printável? : " .format(var), var.isprintable())
